// <auto-generated />
namespace CrudStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration01));
        
        string IMigrationMetadata.Id
        {
            get { return "202211071434087_migration01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
